version: '3.8'

services:
  pg-dan:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pg-dan      
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - dan-db-network

  pgadmin-dan:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: mdomingu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgdan
    ports:
      - "8032:80"
    depends_on:
      - pg-dan
    networks:
      - dan-db-network

networks:
  dan-db-network:
    driver: bridge
