version: '3.8'

services:

  ms-usuarios:
    build:
      context: ../ms-usuarios/
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dandb:3306/dan
      - spring.profiles.active=default
    networks:
      - dan-db-network
    deploy:
      mode: replicated
      replicas: 2

  ms-productos:
    build:
      context: ../dan-ms-productos/
      dockerfile: ./Dockerfile
    ports:
      - 9200:3000
    environment:
      - DB_PASS="pgpassword"
      - DB_USER="pguser"
      - DB_NAME="pg-dan"
      - DB_PORT="5432"
    networks:
      - dan-db-network

  ms-pedidos:
    build:
      context: ../ms-pedidos/
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=mongodb://root:dan@localhost:27017/dan-pedidos?authSource=admin
      - spring.profiles.active=default
    networks:
      - dan-db-network
    deploy:
      mode: replicated
      replicas: 2

  dan-appui:
    container_name: dan-appui
    build:
      context: ../dan-appui/
      dockerfile: ./Dockerfile
    ports:
      - 9500:3000
    networks:
      - dan-db-network

networks:
  dan-db-network:
    driver: bridge